### ISSUE TITLE
Settings don't work in 1.8.7

### ISSUE THREAD

**Issue by Destroy666x** [tommm/flpavatar#5]
Which fixed the checkbox setting type, but this plugin used its own solution that conflicts now.

**Comment by Destroy666x** [comment]
Or rather other plugin's fault - FAStyle is not compatible.

**Comment by Cu8eR** [comment]
@Destroy666x - I cannot confirm - I ue FASTstyle (latest version) and flpavatar plugin together - settings wroks fine.

Latest MyBB 1.8.7 and php 7

**Comment by Destroy666x** [comment]
I don't think you're using the latest version because disabling FASTStyle fixed it for 100%.

**Comment by Cu8eR** [comment]
Latest version of FASTstyle from MyBB mod site and latest GitHub version of flp_avatar. Works fine... maybe any steps how to reproduce? Do you mean the settings located in ACP -> General configuration, right?

**Comment by Destroy666x** [comment]
Steps:
1. Save flp_avatar `php` setting
2. It won't be saved
